
desired_v: 0.8 # desired velocity

ll: 0.60854 # ll of the car
# dt: 0.05
rho: 1 # 1.0 # J = (x-x_r)^2+ (y-y_r)^2 + rho * (phi-phi_r)^2
# N: 40 # horizon
rhoN: 1.0

# lower and upper bound
v_max: 4.0
a_max: 1.0
delta_max: 0.33 # 0.58
ddelta_max: 0.5  # 1.3 # i dont know

# ctrl delay
delay: 0.4  # ??? set 0 will cause BUGS

# true for nmpc, false for qp
nmpc: true
