
# Control
MPC_N:                      40
MPC_dt:                     0.05
desired_v:                  0.8 
ll:                         0.60854     # ll of the car
rho:                        1.0         # J = (x-x_r)^2+ (y-y_r)^2 + rho * (phi-phi_r)^2
rhoN:                       1.0
v_max:                      2.0         # lower and upper bound
a_max:                      1.0
delta_max:                  0.58
ddelta_max:                 1.3         # i dont know
delay:                      0.125       # ctrl delay
nmpc:                       true        # true for nmpc, false for qp